#ifndef ANIMAL_CONFIG_H
#define ANIMAL_CONFIG_H

// --- HERBIVORE CONSTANTS ---
const int HERBIVORE_BASE_HP = 30;
const int HERBIVORE_BASE_DMG = 2;
const int HERBIVORE_BASE_SIGHT = 7;
const int HERBIVORE_BASE_SPEED = 1;
const int HERBIVORE_MAX_ENERGY = 50;
const int HERBIVORE_STARTING_ENERGY = 30;
const int HERBIVORE_REPRODUCE_ENERGY_COST = 15;
const float HERBIVORE_REPRODUCE_ENERGY_PERCENTAGE = 0.75f;
const int HERBIVORE_MIN_REPRODUCE_AGE = 3;
const int HERD_DETECTION_RADIUS = 10;
const int HERD_BONUS_RADIUS = 3;
const int HERD_HP_BONUS_PER_MEMBER = 5;
const float HERBIVORE_FOOD_SEEK_THRESHOLD_PERCENTAGE = 0.75f;

// Herbivore nutritional value constants
const int HERBIVORE_BASE_NUTRITIONAL_VALUE = 45;
const int HERBIVORE_PRIME_AGE = 8;
const int HERBIVORE_PENALTY_PER_YEAR = 2;
const int HERBIVORE_MINIMUM_VALUE = 10;

// --- CARNIVORE CONSTANTS ---
const int CARNIVORE_BASE_HP = 80;
const int CARNIVORE_BASE_DMG = 25;
const int CARNIVORE_BASE_SIGHT = 5;
const int CARNIVORE_BASE_SPEED = 2;
const int CARNIVORE_MAX_ENERGY = 100;
const int CARNIVORE_STARTING_ENERGY = 70;
const int CARNIVORE_REPRODUCE_ENERGY_COST = 35;
const float CARNIVORE_REPRODUCE_ENERGY_PERCENTAGE = 0.70f;
const int CARNIVORE_MIN_REPRODUCE_AGE = 10;
const int OMNIVORE_PACK_THREAT_SIZE = 3;

// Carnivore nutritional value constants
const int CARNIVORE_BASE_NUTRITIONAL_VALUE = 50;
const int CARNIVORE_PRIME_AGE = 25;
const int CARNIVORE_PENALTY_PER_YEAR = 1;
const int CARNIVORE_MINIMUM_VALUE = 15;

// --- OMNIVORE CONSTANTS ---
const int OMNIVORE_BASE_HP = 60;
const int OMNIVORE_BASE_DMG = 15;
const int OMNIVORE_BASE_SIGHT = 6;
const int OMNIVORE_BASE_SPEED = 1;
const int OMNIVORE_MAX_ENERGY = 80;
const int OMNIVORE_STARTING_ENERGY = 50;
const int OMNIVORE_REPRODUCE_ENERGY_COST = 25;
const int OMNIVORE_PACK_HUNT_SIZE = 3;
const float OMNIVORE_REPRODUCE_ENERGY_PERCENTAGE = 0.85f;
const int OMNIVORE_MIN_REPRODUCE_AGE = 8;
const float OMNIVORE_FOOD_SEEK_THRESHOLD_PERCENTAGE = 0.80f;

// Omnivore nutritional value constants
const int OMNIVORE_BASE_NUTRITIONAL_VALUE = 35;
const int OMNIVORE_PRIME_AGE = 15;
const int OMNIVORE_PENALTY_PER_YEAR = 1;
const int OMNIVORE_MINIMUM_VALUE = 10;

#endif // ANIMAL_CONFIG_H